#!/usr/bin/env python3
"""Banco de estrés de 200 preguntas, dificultad creciente, ancladas en datos
reales del árbol. FAIL = el router no entendió la pregunta ("No he sabido
responder…"). "No consta…" cuenta como PASS (entendió, pero no hay dato)."""

import re
import sys
from pathlib import Path

BASE = Path(__file__).parent.parent
sys.path.insert(0, str(BASE / "backend"))
import database  # noqa: E402
from query_router import QueryRouter  # noqa: E402

QUESTIONS = [
    # ---------- Tier 1 (1-40): básicas, una relación / dato vital ----------
    "¿Quiénes eran los padres de Emili Godes Hurtado?",
    "¿Quién era el padre de Artur Godes Caballeria?",
    "¿Cómo se llamaba la madre de Ernest Godes Hurtado?",
    "¿Qué hijos tuvo Francesc Godes Martí?",
    "¿Quiénes eran los hermanos de Rosa Godes Hurtado?",
    "¿Dónde nació Emili Godes Hurtado?",
    "¿Dónde murió Artur Godes Caballeria?",
    "¿Cuándo nació Pasqual Godes Gomis?",
    "¿De qué trabajaba Emili Godes Hurtado?",
    "¿Dónde vivía Mercè Godes Caballeria?",
    "¿Qué profesión tenía Ernest Godes Hurtado?",
    "¿Cuántos hijos tuvo Rosa Segura Falomir?",
    "¿Cuántos hermanos tenía Emili Godes Hurtado?",
    "¿Quién fue el padre de Pasqual Godes Gomis?",
    "¿Quiénes son los hijos de Artur Godes Caballeria?",
    "¿En qué año nació Ernest Godes Hurtado?",
    "¿A qué se dedicaba Jesus Godes Diago?",
    "¿Cuándo murió Emilia Hurtado Giró?",
    "¿Dónde nació Pasqual Godes Segura?",
    "¿Quién era la madre de Mercè Godes Caballeria?",
    "¿Qué oficio tenía Pasqual Godes Gomis?",
    "¿Quiénes fueron los padres de Rosa Caballeria Madiroles?",
    "¿Tuvo hijos Pau Godes Caballeria?",
    "¿Dónde residía Antònia Diago Almuzara?",
    "¿Cuál era la profesión de Ramón Godes Hurtado?",
    "¿Quiénes eran los hermanos y hermanas de Dolors Godes Caballeria?",
    "¿En qué trabajaba Josep Maria Godes Hurtado?",
    "¿Dónde nació Rosa Godes Hurtado?",
    "¿Quién fue la madre de Artur Godes Caballeria?",
    "¿Qué hijos tuvo Pasqual Godes Segura?",
    "¿Cuándo nació Mercè Godes Caballeria?",
    "¿Dónde murió Pasqual Godes Gomis?",
    "¿Cuántos hijos tuvo Nicómedes Diago Marín?",
    "¿Quién era el padre de Emilia Hurtado Giró?",
    "¿De qué trabajaba Enric Godes Maté?",
    "¿Dónde vivía Emili Godes Hurtado?",
    "¿Quiénes eran los hijos de Rosa Segura Falomir?",
    "¿En qué año murió Artur Godes Caballeria?",
    "¿Qué hermanos tenía Pau Godes Caballeria?",
    "¿Dónde nació Emilia Hurtado Giró?",
    # ---------- Tier 2 (41-90): modificadores, políticos, conteos, matrimonio ----------
    "¿Quiénes eran los abuelos de Emili Godes Hurtado?",
    "¿Quién era el abuelo paterno de Rosa Godes Hurtado?",
    "¿Quién fue la abuela materna de Ernest Godes Hurtado?",
    "¿Quiénes eran los bisabuelos de Emili Godes Hurtado?",
    "¿Qué tíos tenía Emili Godes Hurtado?",
    "¿Quiénes eran los primos de Mercè Godes Caballeria?",
    "¿Quiénes son los sobrinos de Emili Godes Hurtado?",
    "¿Quiénes eran los nietos de Artur Godes Caballeria?",
    "¿Con quién se casó Artur Godes Caballeria?",
    "¿Cuándo se casó Emili Godes Hurtado?",
    "¿Dónde se casó Pasqual Godes Gomis?",
    "¿Quién fue la esposa de Ernest Godes Hurtado?",
    "¿Qué abuelos tenía Mercè Godes Caballeria?",
    "¿Cuántos domicilios tuvo Emili Godes Hurtado?",
    "¿Qué domicilios tuvo Mercè Godes Caballeria?",
    "¿Quiénes eran los suegros de Artur Godes Caballeria?",
    "¿Quiénes eran los primos hermanos de Rosa Godes Hurtado?",
    "¿Quién era el cónyuge de Emilia Hurtado Giró?",
    "¿Cuántos nietos tuvo Francesc Godes Martí?",
    "¿Quiénes eran los tíos y tías de Rosa Godes Hurtado?",
    "¿Quién era la abuela paterna de Emili Godes Hurtado?",
    "¿Quiénes fueron los nietos de Pasqual Godes Gomis?",
    "¿Con quién se casó Rosa Godes Hurtado?",
    "¿En qué año se casó Artur Godes Caballeria?",
    "¿Quiénes eran los hijos de Francesc Godes Martí y Rosa Segura Falomir?",
    "¿Cuántos hijos tuvieron Artur Godes Caballeria y Emilia Hurtado Giró?",
    "¿Quién era el yerno de Pasqual Godes Gomis?",
    "¿Quién fue la nuera de Francesc Godes Martí?",
    "¿Quiénes eran los cuñados de Emili Godes Hurtado?",
    "¿Quiénes son los bisnietos de Pasqual Godes Segura?",
    "¿Quiénes eran los primos segundos de Emili Godes Hurtado?",
    "¿Qué personas nacieron en Benabarre?",
    "¿Qué personas murieron en Barcelona?",
    "¿Quién nació en 1895?",
    "¿Quiénes son las personas vivas de la familia?",
    "¿Qué residencias tuvo Jesus Godes Diago?",
    "¿Dónde estuvo domiciliado Pau Godes Caballeria?",
    "¿Quién era el abuelo materno de Rosa Godes Hurtado?",
    "¿Cuántos hermanos tenía Mercè Godes Caballeria?",
    "¿Qué edad tenía Artur Godes Caballeria cuando se casó?",
    "¿A qué edad tuvo su primer hijo Emilia Hurtado Giró?",
    "¿De qué matrimonio nació Emili Godes Hurtado?",
    "¿Quiénes eran los padres de Mercè Godes Caballeria y dónde se casaron?",
    "¿Quién era mayor, Emili Godes Hurtado o Ernest Godes Hurtado?",
    "¿Qué parentesco tenía Emili Godes Hurtado con Rosa Godes Hurtado?",
    "¿Eran primos Emili Godes Hurtado y Mercè Godes Caballeria?",
    "¿Quién fue el hijo mayor de Artur Godes Caballeria?",
    "¿Cuál fue el primer hijo de Francesc Godes Martí?",
    "¿Quién fue el último hijo de Rosa Segura Falomir?",
    "¿Qué hijos de Artur Godes Caballeria nacieron en Barcelona?",
    # ---------- Tier 3 (91-150): multi-hop, comparaciones, eventos ----------
    "¿Quién era el padre de la madre de Emili Godes Hurtado?",
    "¿Cómo se llamaban los cuatro abuelos de Rosa Godes Hurtado?",
    "¿Quién vivió más años, Pasqual Godes Gomis o Francesc Godes Martí?",
    "¿Cuántos descendientes directos tuvo Artur Godes Caballeria?",
    "¿Tenía descendencia Pau Godes Caballeria?",
    "¿Qué actividad militar tuvo Emili Godes Hurtado?",
    "¿Dónde está enterrado Artur Godes Caballeria?",
    "¿Cuándo fue bautizado Emili Godes Hurtado?",
    "¿Quiénes fueron los padrinos de Rosa Godes Hurtado?",
    "¿Qué eventos hay registrados de Emili Godes Hurtado?",
    "¿Dónde vivía Mercè Godes Caballeria al final de su vida?",
    "¿Cuál fue el primer domicilio de Emili Godes Hurtado?",
    "¿Cuántos años vivió Pasqual Godes Gomis?",
    "¿En qué posición entre sus hermanos nació Emili Godes Hurtado?",
    "¿Quién era el padre de Pasqual Godes Gomis y dónde se casó?",
    "¿Qué notas biográficas hay sobre Emili Godes Hurtado?",
    "¿Quién aparece como pareja de Artur Godes Caballeria?",
    "¿Con quién acabó casándose Ernest Godes Hurtado?",
    "¿Qué personas se llaman Rosa en el árbol?",
    "¿Qué Godes nacieron en Barcelona?",
    "¿Quiénes nacieron y murieron en Barcelona?",
    "¿Qué grado de parentesco había entre Emili Godes Hurtado y Mercè Godes Caballeria?",
    "¿Cuántos hijos llegó a tener Francesc Godes Martí?",
    "¿Quién era el tío abuelo de Emili Godes Hurtado?",
    "¿Quiénes eran los tatarabuelos de Emili Godes Hurtado?",
    "¿Hay tataranietos documentados de Pasqual Godes Segura?",
    "¿Quién fue la bisabuela materna de Emili Godes Hurtado?",
    "¿Quién nació el mismo año que Emili Godes Hurtado?",
    "¿Qué personas nacieron en la década de 1890?",
    "¿Cuántas personas nacieron en Benabarre?",
    "¿Cuál es la persona más longeva del árbol?",
    "¿Quién es la persona más joven?",
    "¿Cuál es la media de hijos?",
    "¿Hay más hombres o mujeres?",
    "¿Qué persona tuvo más hijos?",
    "¿Cuántos miembros tiene la familia Godes?",
    "¿Qué matrimonio tuvo más descendencia documentada?",
    "¿Cuántos nacimientos hay en la década de 1900?",
    "¿Cuántos fallecimientos hay en la década de 1920?",
    "¿Quién nació antes, Emili Godes Hurtado o Ernest Godes Hurtado?",
    "¿A qué edad tuvo su primer hijo Artur Godes Caballeria?",
    "¿Qué edad tenía Emilia Hurtado Giró al casarse?",
    "¿Quiénes eran los abuelos de Emili Godes Hurtado y en qué años nacieron?",
    "¿Qué hijos de Francesc Godes Martí nacieron en Morella?",
    "¿Dónde nació Emili Godes Hurtado y qué ocupación consta en su ficha?",
    "¿Quiénes eran los padres de Rosa Godes Hurtado y dónde se casaron?",
    "¿Cuántos hijos sobrevivieron a Francesc Godes Martí?",
    "¿Quién era mayor cuando se casaron, Artur Godes Caballeria o Emilia Hurtado Giró?",
    "¿Cuántas personas del árbol se llaman Josep?",
    "¿Quién fue la primera hija de Artur Godes Caballeria?",
    "¿Qué nombre de pila empieza por A?",
    "¿Quién falleció en 1925?",
    "¿Qué parejas se casaron en Barcelona?",
    "¿Quién murió en Barcelona en 1970?",
    "¿Quién nació en Benabarre en 1850?",
    "¿Qué personas no tienen fecha de nacimiento conocida?",
    "¿Cuántas personas tienen fecha de nacimiento conocida frente a las que no?",
    "¿Quiénes participaron en la guerra?",
    "¿Qué relación tenía Emili Godes Hurtado con los padres de Rosa Godes Hurtado?",
    "¿Quién era la cuñada de Emili Godes Hurtado?",
    # ---------- Tier 4-5 (151-200): analíticas, compuestas, muy difíciles ----------
    "¿Qué rama de la familia tuvo más hijos?",
    "¿Qué lugar de nacimiento tiene más variantes de escritura?",
    "¿Qué porcentaje del árbol corresponde a personas con primer apellido Godes?",
    "¿En qué puesto del ranking de descendencia se sitúa Artur Godes Caballeria?",
    "¿Cuántos hijos tuvo Artur Godes Caballeria en comparación con la media del árbol?",
    "¿Cuántos hermanos tenía Emili Godes Hurtado y cómo se compara con su generación?",
    "¿Qué edad vivió Pasqual Godes Gomis y está entre las más altas del árbol?",
    "¿Qué pareja tuvo exactamente 10 hijos y en qué posición queda por tamaño familiar?",
    "¿Cuántas personas murieron en Barcelona y qué relevancia tiene ese lugar?",
    "¿Cuál fue antes: el nacimiento de Emili Godes Hurtado o el de Ernest Godes Hurtado?",
    "¿Qué nombres compuestos son los más repetidos?",
    "¿Cuántas personas tienen dos apellidos iguales?",
    "¿Quién es el bisnieto mayor de Pasqual Godes Segura?",
    "¿Hay tataranietos documentados de Francesc Godes Martí?",
    "¿Quiénes son los consuegros de Pasqual Godes Gomis?",
    "¿Quién fue la prima segunda de alguien de la rama Hurtado?",
    "¿Qué personas nacieron en Benabarre y murieron fuera de Benabarre?",
    "Busco a las personas que nacieron en Barcelona y también murieron allí",
    "¿Qué parejas del árbol tuvieron diez o más hijos?",
    "¿Qué rama tuvo más hijos: la de Artur Godes Caballeria y Emilia Hurtado Giró o la siguiente pareja del ranking?",
    "¿Hay alguna persona Godes con descendencia documentada?",
    "¿Cuántas personas se llaman Maria en el árbol?",
    "¿Qué edad tenía Artur Godes Caballeria cuando nació su primer hijo y está por encima o por debajo de la media?",
    "¿Quiénes eran los tíos abuelos de Emili Godes Hurtado?",
    "¿Quiénes son los sobrinos nietos de Pasqual Godes Gomis?",
    "¿Qué relación familiar hay entre Pasqual Godes Gomis y Emili Godes Hurtado?",
    "¿Cuál era la cadena ascendente de Emili Godes Hurtado hasta Pasqual Godes Segura?",
    "¿Cuántas generaciones separan a Pasqual Godes Segura de Emili Godes Hurtado?",
    "¿Qué diferencia de edad había entre Emili Godes Hurtado y Ernest Godes Hurtado?",
    "¿Quién era el padrino de bautismo de Emili Godes Hurtado?",
    "¿Qué oficios distintos tuvo Jesus Godes Diago a lo largo de su vida?",
    "¿En qué iglesia se casó Artur Godes Caballeria?",
    "¿Quién de los hijos de Francesc Godes Martí vivió más años?",
    "¿Cuál de los abuelos de Emili Godes Hurtado nació antes?",
    "¿Qué descendientes de Pasqual Godes Segura llegaron a vivir en Barcelona?",
    "¿Quién tuvo más nietos, Artur Godes Caballeria o Francesc Godes Martí?",
    "¿Cuántos años de diferencia hay entre el nacimiento de Pasqual Godes Gomis y el de su hijo Pasqual Godes Segura?",
    "¿Qué antepasados comunes comparten Emili Godes Hurtado y Mercè Godes Caballeria?",
    "¿Cuál es el matrimonio más antiguo documentado del árbol?",
    "¿Qué personas de la familia nacieron fuera de Cataluña?",
    "¿Cuántos descendientes en total tiene Pasqual Godes Segura?",
    "¿Quién fue el primer Godes nacido en Barcelona?",
    "¿Qué hijos tuvo en común la pareja formada por Francesc Godes Martí y Rosa Segura Falomir?",
    "¿Cuál es el apellido más frecuente en el árbol?",
    "¿Qué personas nacieron el mismo día que Emili Godes Hurtado?",
    "¿Quién vivió en más domicilios distintos a lo largo de su vida?",
    "¿Qué generación de la familia fue la más numerosa?",
    "¿Cuál fue la causa de muerte de Artur Godes Caballeria?",
    "¿Qué miembros de la familia se dedicaron a la fotografía?",
    "¿Quién es el pariente vivo de más edad de la familia?",
]


def main():
    assert len(QUESTIONS) == 200, f"esperaba 200, hay {len(QUESTIONS)}"
    conn = database.get_connection(str(BASE / "data" / "godesia.db"))
    router = QueryRouter(conn)
    fails = []
    for i, q in enumerate(QUESTIONS, 1):
        ans = router.route(q).get("answer", "") or ""
        plain = re.sub(r"<[^>]+>", "", ans)
        if plain.startswith("No he sabido responder"):
            fails.append((i, q, plain))
    print(f"Resueltas: {200 - len(fails)}/200  ·  No entendidas: {len(fails)}")
    if fails:
        print("\n--- NO ENTENDIDAS (no_match) ---")
        for i, q, _ in fails:
            tier = ("T1" if i <= 40 else "T2" if i <= 90 else "T3" if i <= 150 else "T4/5")
            print(f"  [{tier} #{i}] {q}")
    return fails


if __name__ == "__main__":
    main()
